services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:

